<?php if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_header-section',
        'title' => 'Header Section',
        'fields' => array (
            array (
                'key' => 'field_54afbe4d243fc',
                'label' => 'Banner Background Image',
                'name' => 'banner_image',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'full',
                'library' => 'all',
            ),
            array (
                'key' => 'field_54afbe8a243fd',
                'label' => 'Banner Main Image',
                'name' => 'banner_main_image',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_54afbef2243fe',
                'label' => 'Banner Heading',
                'name' => 'banner_heading',
                'type' => 'text',
                'required' => 1,
                'default_value' => 'Enter you page details',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54afbf44243ff',
                'label' => 'Banner Background colour',
                'name' => 'banner_background_colour',
                'type' => 'color_picker',
                'default_value' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_type',
                    'operator' => '==',
                    'value' => 'top_level',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 1,
    ));

    register_field_group(array (
        'id' => 'acf_action-content',
        'title' => 'Action Content',
        'fields' => array (
            array (
                'key' => 'field_54b6379169694',
                'label' => 'CTA Text',
                'name' => 'cta_text',
                'type' => 'text',
                'instructions' => 'Enter the call to action text to be added to the main page',
                'default_value' => 'Create your CARD NAME# card now ,',
                'placeholder' => 'Mumblecore occupy letterpress, single-origin coffee vegan blog artisan typewriter. Mlkshk bespoke blog distillery lumbersexual, single-origin coffee gastropub drinking vinegar narwhal put a bird on it letterpress occupy crucifix seitan.',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => 300,
            ),
            array (
                'key' => 'field_54b6381e69695',
                'label' => 'CTA Button Text',
                'name' => 'cta_button_text',
                'type' => 'text',
                'instructions' => 'Enter the message on the button',
                'default_value' => 'Enter the message on the button',
                'placeholder' => 'Enter the message on the button',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => 75,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '4',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 2,
    ));

    register_field_group(array (
        'id' => 'acf_marketing-content-1',
        'title' => 'Marketing Content 1',
        'fields' => array (
            array (
                'key' => 'field_54b63ca718366',
                'label' => 'Subsection 1 - Icon',
                'name' => 'subsection_1_-_icon',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_54b63cf218367',
                'label' => 'Subsection 1 - Heading',
                'name' => 'subsection_1_-_heading',
                'type' => 'text',
                'required' => 1,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b63d1318368',
                'label' => 'Subsection 1 - Content',
                'name' => 'subsection_1_-_content',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b63d4d1836a',
                'label' => 'Subsection 2 - Icon',
                'name' => 'subsection_2_-_icon',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_54b63d671836b',
                'label' => 'Subsection 2 - Heading',
                'name' => 'subsection_2_-_heading',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b63d7b1836c',
                'label' => 'Subsection 2 - Content',
                'name' => 'subsection_2_-_content',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b63ff11836d',
                'label' => 'Subsection 3 - Icon',
                'name' => 'subsection_3_-_icon',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_54b640371836e',
                'label' => 'Subsection 3 - Heading',
                'name' => 'subsection_3_-_heading',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b6404a1836f',
                'label' => 'Subsection 3 - Content',
                'name' => 'subsection_3_-_content',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 3,
    ));
}
?>
